<?php

/*
 * This file is licensed under GPLv2+.
*/
require_once('mas.inc');

/**
 * @file
 * Provides MAS(SciTech) interface for drupal.
 */

function mas_permission() {
	return array(
		'send sms' => array(
			'title' => t('Send SMS to others'),
		),
	);
}

function mas_menu() {
	$items['admin/config/services/mas'] = array(
		'title' => 'mas settings',
		'description' => 'various mas settings.',
		'access callback' => 'user_access',
		'access arguments' => array('access administration pages'),
		'page callback' => 'drupal_get_form',
		'page arguments' => array('mas_admin_form'),
	);
	$items['user/%user/sms'] = array(
		'type' => MENU_LOCAL_TASK,
		'title' => 'Short Messenger Service',
		'description' => 'SMS communication log',
		'access callback' => 'mas_user_sms_access',
		'access arguments' => array(1),
		'page callback' => 'mas_user_sms',
		'page arguments' => array(1),
	);
	return $items;
}

/**
 * Implementation of hook_uninstall().
 */
function mas_uninstall() {
	$settings=array(
		'code', 'extcode', 'applicationid'
	);
	foreach($settings as $s) {
		variable_del('mas_'.$s);
	}
}

function mas_admin_form($form, $form_state) {
	$form=array(
		'#submit' => array('mas_admin_form_submit'),
		'#validate' => array('mas_admin_form_validate'),
	);
	$form['code'] = array(
		'#type' => 'textfield',
		'#title' => t('Mas Group Number on sending'),
		'#description' => t('The leading number of sender.'),
		'#default_value' => variable_get('mas_code'),
		'#maxlength' => 12,
		'#size' => 40,
		'#required' => TRUE,
	);
	$form['extcode'] = array(
		'#type' => 'textfield',
		'#title' => t('ExtCode'),
		'#description' => t('The number after leading number of sender.'),
		'#default_value' => variable_get('mas_extcode'),
		'#required' => TRUE,
		'#maxlength' => 4,
		'#size' => 40,
	);
	return system_settings_form($form);
}

function mas_admin_form_validate($form, $form_state) {
	if(preg_match('@^106[0-9]{9}$@', $form_state['values']['code']) !== 1) {
		form_set_error('code', t('The @field you have entered is not valid.',array('@field' => t('Mas Number on sending'))));
	}
	if(preg_match('@^[0-9]{1,4}$@', $form_state['values']['extcode']) !== 1) {
		form_set_error('extcode', t('The @field you have entered is not valid.',array('@field' => t('ExtCode'))));
	}
}

function mas_admin_form_submit($form, $form_state) {
	$settings=array(
		'code', 'extcode', 'applicationid'
	);
	foreach($settings as $s) {
		variable_set('mas_'.$s,trim($form_state['values'][$s]));
	}
}

function mas_user_sms_access($user) {
	if(user_access('send sms')) {
		$phonenumbers=module_invoke_all('get_phone_number',$user);
		if(empty($phonenumbers)) return FALSE;
		else return TRUE;
	} else return FALSE;
}

function mas_user_sms($user) {
	$host=$_SERVER['HTTP_HOST'];
	$appdigest=substr(md5($_SERVER['SERVER_ADDR'].$_SERVER['REQUEST_URI']),8,16); 
	$query=db_query('SELECT EXISTS(SELECT * FROM {sms_inbox1} inbox INNER JOIN {sms_sent1} sentbox ON '.
		'inbox.SOURCEADDR=sentbox.DESTADDR AND inbox.EXTCODE=sentbox.EXTCODE '.
		'WHERE inbox.EXTCODE=:extcode AND sentbox.SENTRESULT=1 AND sentbox.APPLICATIONID=:appid)',
		array(':extcode'=>variable_get('mas_extcode'), ':appid'=>$appdigest));
	$r=$query->fetchField();
	if($r) {
		$query=db_query('SELECT DESTADDR FROM {sms_sent1} WHERE APPLICATIONID=:appid', array(':appid'=>$appdigest));
		foreach($query as $r) {
			db_update('sms_inbox1')->condition('APPLICATIONID','')->condition('SOURCEADDR',$r->DESTADDR)->fields(array(
				'APPLICATIONID' => $appdigest
			))->execute();
		}
	}
	
	$query=db_query('SELECT * FROM ('.
		'(SELECT 1 AS direction, RECEIVETIME as timestamp, RECEIVETIME as processtime, MESSAGECONTENT as content, 1 as status '.
			'FROM {sms_inbox1} inbox WHERE inbox.APPLICATIONID=:appid) UNION ALL '.
		'(SELECT 2 AS direction, sent.SENTTIME as timestamp, outbox.REQUESTTIME as processtime, outbox.MESSAGECONTENT as content, sent.SENTRESULT as status '.
			'FROM {sms_sent1} sent RIGHT JOIN {sms_outbox1} outbox ON sent.sismsid=outbox.sismsid '.
			'WHERE outbox.APPLICATIONID=:appid) '.
			') combine ORDER BY processtime',
		array(':appid'=>$appdigest));
	drupal_add_css(drupal_get_path('module','mas').'/mas.css');
	$output='';
	foreach($query as $r) {
		$output .=sprintf('<div class="%s"><div class="mas-content %s">%s</div><div class="mas-status">%s</div></div>',
			$r->direction==1?'mas-log-upgoing':'mas-log-downgoing',
			(empty($r->status)||$r->status==1)?'':'error',
			(empty($r->status)?t('Sending: '):'').$r->content,
			empty($r->status)?t('Sending'):($r->status!=1?($r->processtime.sprintf(' (%s)', t('Sent Failed'))):$r->timestamp)
		);
	}
	if(!empty($output))
		$output='<div id="mas-log" style="height: 400px; overflow-y:auto; overflow-x: hidden;">'.$output.'</div>';
	drupal_add_js('jQuery(document).ready(function(){jQuery("#mas-log").scrollTop(jQuery("#mas-log")[0].scrollHeight); jQuery("#edit-content").focus();});',
		array('type'=>'inline'));
	$phonenumbers=module_invoke_all('get_phone_number',$user);
	if(!empty($phonenumbers))
		$output.=drupal_render(drupal_get_form('mas_send_sms_form', $user, $phonenumbers[0], $appdigest));
	return $output;
}

function mas_send_sms_form($form, $form_state, $user, $phonenumbers, $appid) {
	$form['#user']=$user;
	$form['#phonenumbers']=array_values($phonenumbers);
	$form['#appid']=$appid;
	$form['content']=array(
		'#type' => 'textfield',
		'#size' => '94',
		'#required' => TRUE,
		'#description' => t('Input the message you want to send and press Enter when ready.'),
	);
	$form['send']=array(
		'#type' => 'submit',
		'#attributes' => array('style'=>'display: none')
	);
	return $form;
}

function mas_send_sms_form_submit($form, $form_state) {
	$content=trim($form_state['values']['content']);
	if(isset($form['#contentprefix']))
		$content=format_username($GLOBALS['user']).': '.$form['#contentprefix'].$content;
	foreach($form['#phonenumbers'] as $phonenumber) {
		db_insert('sms_outbox1')->fields(array(
			'sismsid' => mt_rand(0,pow(10,10)-1),
			'EXTCODE' => variable_get('mas_extcode'),
			'DESTADDR' => $phonenumber,
			'MESSAGECONTENT' => $content,
			'REQDELIVERYREPORT' => 1,
			'MSGFMT' => 16,
			'SENDMETHOD' => 1,
			'REQUESTTIME' => strftime('%Y-%m-%d %H:%M:%S'),
			'APPLICATIONID' => $form['#appid'],
			'FLAG' => 0
		))->execute();
	}
	$content=trim($form_state['values']['content']);
	if(strlen($content)>10)
		$content=mb_substr($content,0,10,'UTF-8').'...';
	watchdog('mas',
		'Sent message !content to !user.',
		array('!content'=>$content, '!user'=>format_username($form['#user'])),
		WATCHDOG_DEBUG,
		l(t('View'), 'user/'.$form['#user']->uid.'/sms')
	);
	if($GLOBALS['user']->uid)
		drupal_set_message(t('Message Request Sent.'));
}

function mas_user_view($user, $view_mode, $langcode) {
	if(mas_user_sms_access($user)) {
		$phonenumbers=module_invoke_all('get_phone_number',$user);
		$appdigest=substr(md5($_SERVER['SERVER_ADDR'].'/user/'.$user->uid.'/sms'),8,16); 
		$user->content['mas']['#weight']=9;
		$user->content['mas']['send']=array(
			'#type' => 'user_profile_item',
			'#title' => t('Short Messenger Service'),
			'#markup' => drupal_render(drupal_get_form('mas_send_sms_form', $user, $phonenumbers[0], $appdigest)),
		);
	}
}

?>
